### ISSUE TITLE
OSError: No pre-trained weights found for perceptual model!

### ISSUE THREAD

**Issue by srinivaspavan9** [weihaox/TediGAN#6]
I got this error in the Playground CoLab notebook. Also, can you help me with training and executing this model in CoLab as i dont have a GPU
![image](https://user-images.githubusercontent.com/34889400/110431291-9a4b1a00-80d3-11eb-831f-76aaf3f0bc7f.png)

**Comment by srinivaspavan9** [comment]
> The three pretrained model should be placed in path`idinvert_pytorch/models/pretrain`. Try this #3: change `MODEL_DIR = os.path.join('models', 'pretrain')` to `MODEL_DIR = os.path.join('idinvert_pytorch', 'models', 'pretrain')` or move manually to this path.

Thanks, it's working but the output images aren't changing with the given description. I am getting the same output of "He is old ". I changed the description to "she has black hair, with a sharp nose and wears lipstick"

![image](https://user-images.githubusercontent.com/34889400/110475532-02672380-8107-11eb-8128-4611f9ce0abb.png)
![image](https://user-images.githubusercontent.com/34889400/110475667-2e82a480-8107-11eb-98b4-6dc38009d19f.png)

**Comment by srinivaspavan9** [comment]
> The `@param` of colab are used to show the default setting. You should assign the parameters by `python invert_v2.py --description="she has black hair, with a sharp nose and wears lipstick"`. I haven't tried to change so many attributes at one time using the default steps and learning rate. I am not sure if the obtained results are satisfactory or not. If you got bad results, you can try to increase the number of iterations or change one attribute at a time and get the final results step by step.

Thanks, it's working. What would be the optimal no of iterations to get the best results?

**Comment by weihaox** [comment]
The released colab is for image generation and manipulation using StyleGAN and CLIP (using a pretrained text encoder instead of training a text encoder as proposed in the paper).  It was inspired by [StyleCLIP](https://github.com/orpatashnik/StyleCLIP/issues/2), whose loss weights are very sensitive and should be chosen case by case. I add the CLIP loss in the instance-level optimization module. The optimization is much more stable than theirs. But still, the obtained results may be unpleasing in some cases, especially the generation process. If your obtained results are not good, you can adjust the learning parameters. _**I cannot give an optimal number of iterations for the best results.**_ The default settings (including the learning rate and iteration number) are not deliberately chosen and the results with the default settings are good enough for most cases. As I see, changing loss_weight_clip may be more helpful to generate meaningful results, rather than increasing the number of iterations.

**_`142_inv.png` is the manipulated or generated result. For manipulation, `142_enc.png` is the inverted image from the encoder; for generation, `142_enc.png` is result of the randomly sampled latent code_** (refer to #5 if you had questions on why the randomly sampled latent code is needed). The codes are for  #5  and pretty ugly now. I havn't changed the function interface of [invert](https://github.com/weihaox/TediGAN/blob/c9d43dcdc54be5ab388f0cb5aa8d5cad26f35c7d/idinvert_pytorch/utils/inverter.py#L166). The image still needs to be loaded for generation. I will clean the codes soon.

**Comment by srinivaspavan9** [comment]
Thanks for the help, I think I need to read the paper again for a better understanding
